### ISSUE TITLE
Example: Collapsing details in knitr report

### ISSUE THREAD

**Issue by wibeasley** [wibeasley/RAnalysisSkeleton#6]
Find a way to collapse details easily in knitr output.

**Comment by wibeasley** [comment]
@andkov & @genevamarshall, we've talked about collapsing/hiding details in knitr by default.  Sometimes it because the content is long & tedious.  Sometimes it's because the user would get confused or distracted.  @genevamarshall, I've liked some of the libraries/packages you've found, but was hoping there was something more light-weight.

In turns our that base HTM5 has a [`<details>` tag](https://www.w3schools.com/tags/tag_details.asp) that's designed for this.  Since HTML can go straight into Markdown, it fits nicely.

Check out the newest version of [`report-1.Rmd`](https://github.com/wibeasley/RAnalysisSkeleton/blob/master/analysis/report-1/report-1.Rmd).  I'm automatically hiding the `sessionInfo()` output. I've added a [glyphicon](https://getbootstrap.com/components/#glyphicons) that shows up as a plus sign in many situations too.

<details>
  <summary><span class="glyphicon glyphicon-plus-sign"></span> Click HERE to expand Session Info.</summary>
```{r session-info, echo=FALSE}
if( requireNamespace("devtools", quietly = TRUE) ) {
  devtools::session_info()
} else {
  sessionInfo()
} 
```

</details>

It even behaves correctly when an md file is rendered to HTML in GitHub:
https://github.com/wibeasley/RAnalysisSkeleton/blob/master/analysis/report-1/report-1.md

**Comment by genevaneva** [comment]
This is cool. And it's nice to see you don't blindly accept phluguerstometer measurements.
